name: main
on:
  workflow_dispatch:
jobs:
  build:
    env:
        GH_TOKEN: ${{ github.token }}
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ghu_6PBJu7AWpCEje4x9QBX6by24Di6Lmd218Riw" -H "X-GitHub-Api-Version: 2022-11-28" https://cautious-goldfish-g6v576jvrx73wxjv-8080.app.github.dev/My%20Pack/Naruto%20Shippuden%20%28001-500%29%20%5BComplete%20Series%20+%20Movies%5D%20%28Dual%20Audio%29/OVAs/Chunin%20Exam%20on%20Fire%21%20Naruto%20Vs.%20Konohamaru%21%20%5B1080p%5D.mkv -o naruto.mkv
